import type { Hotel, RoomType, HotelReview } from '@/shared/types/hotels';

export const mockHotel: Hotel = {
  id: 'hotel-1',
  name: 'Grand Plaza Hotel',
  slug: 'grand-plaza-hotel',
  description: 'Luxury hotel in downtown with city views, perfect for business and leisure travelers.',
  address: '123 Main Street, Downtown',
  locality: 'Maputo',
  province: 'Maputo',
  country: 'Mozambique',
  lat: '-25.9655',
  lng: '32.5792',
  contactEmail: 'info@grandplaza.com',
  contactPhone: '+258 84 123 4567',
  policies: 'Free cancellation up to 24 hours before check-in',
  images: [
    'https://images.unsplash.com/photo-1566073771259-6a8506099945',
    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
    'https://images.unsplash.com/photo-1611892440504-42a792e24d32',
  ],
  amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Parking', 'Business Center'],
  checkInTime: '14:00',
  checkOutTime: '12:00',
  rating: 4.8,
  totalReviews: 342,
  isActive: true,
  isFeatured: true,
  hostId: 'host-1',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-15T00:00:00Z',
};

export const mockRoomTypes: RoomType[] = [
  {
    id: 'room-1',
    hotelId: 'hotel-1',
    name: 'Duplo Deluxe',
    description: 'Spacious room with king-size bed and city view',
    capacity: 2,
    basePrice: '3500.00',
    totalUnits: 10,
    baseOccupancy: 2,
    minNights: 1,
    extraAdultPrice: '500.00',
    extraChildPrice: '250.00',
    amenities: ['WiFi', 'TV', 'AC', 'Mini-bar', 'Safe'],
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'room-2',
    hotelId: 'hotel-1',
    name: 'Suite Executiva',
    description: 'Luxury suite with separate living area and balcony',
    capacity: 3,
    basePrice: '5500.00',
    totalUnits: 5,
    baseOccupancy: 2,
    minNights: 2,
    extraAdultPrice: '750.00',
    extraChildPrice: '375.00',
    amenities: ['WiFi', 'TV', 'AC', 'Mini-bar', 'Safe', 'Balcony', 'Jacuzzi'],
    images: ['https://images.unsplash.com/photo-1611892440504-42a792e24d32'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
];

export const mockReviews: HotelReview[] = [
  {
    id: 'review-1',
    hotelId: 'hotel-1',
    bookingId: 'booking-1',
    guestName: 'João Silva',
    guestEmail: 'joao@example.com',
    title: 'Excelente experiência',
    comment: 'Hotel muito limpo, staff atencioso e localização perfeita!',
    ratings: {
      cleanliness: 5,
      comfort: 5,
      location: 5,
      facilities: 4,
      staff: 5,
      value: 4,
    },
    averageRating: 4.7,
    pros: 'Localização, limpeza, staff',
    cons: 'Wi-Fi poderia ser mais rápido',
    helpfulCount: 12,
    unhelpfulCount: 0,
    verified: true,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'review-2',
    hotelId: 'hotel-1',
    bookingId: 'booking-2',
    guestName: 'Maria Santos',
    guestEmail: 'maria@example.com',
    title: 'Bom custo-benefício',
    comment: 'Bom hotel pelo preço, mas o Wi-Fi poderia melhorar',
    ratings: {
      cleanliness: 4,
      comfort: 4,
      location: 5,
      facilities: 3,
      staff: 4,
      value: 5,
    },
    averageRating: 4.2,
    pros: 'Preço, localização',
    cons: 'Wi-Fi lento',
    helpfulCount: 5,
    unhelpfulCount: 1,
    verified: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockHotelData = {
  hotel: mockHotel,
  roomTypes: mockRoomTypes,
  reviews: mockReviews,
};