#!/bin/bash
# Instruções de setup para o módulo de Hotéis e Event Spaces

echo "🏨 Setup do Módulo de Hotéis e Event Spaces"
echo "=========================================="
echo ""

# Verificar se as dependências principais estão instaladas
echo "✓ Verificando dependências..."

# Dependências necessárias (já devem estar instaladas)
REQUIRED_PACKAGES=(
  "@tanstack/react-query"
  "react"
  "react-dom"
  "wouter"
  "@radix-ui/react-tabs"
  "@radix-ui/react-dialog"
  "lucide-react"
  "tailwindcss"
  "typescript"
)

echo ""
echo "✓ Dependências verificadas"
echo ""

# Mostrar estrutura criada
echo "📁 Estrutura criada:"
echo ""
echo "src/shared/types/"
echo "  ├── hotels.ts                    (Tipos para hotéis)"
echo "  └── event-spaces.ts             (Tipos para event spaces)"
echo ""
echo "src/shared/components/"
echo "  ├── hotels/"
echo "  │   ├── HotelCard.tsx"
echo "  │   ├── HotelSearch.tsx"
echo "  │   ├── HotelGallery.tsx"
echo "  │   ├── RoomTypeCard.tsx"
echo "  │   └── index.ts"
echo "  └── event-spaces/"
echo "      ├── EventSpaceCard.tsx"
echo "      └── index.ts"
echo ""
echo "src/apps/main-app/features/"
echo "  ├── hotels/"
echo "  │   ├── pages/"
echo "  │   │   ├── HotelsSearchPage.tsx"
echo "  │   │   └── HotelDetailPage.tsx"
echo "  │   └── hooks/"
echo "  │       └── useHotels.ts"
echo "  └── event-spaces/"
echo "      ├── pages/"
echo "      │   ├── EventSpacesSearchPage.tsx"
echo "      │   └── EventSpaceDetailPage.tsx"
echo "      └── hooks/"
echo "          └── useEventSpaces.ts"
echo ""
echo "src/apps/admin-app/"
echo "  ├── pages/hotel-management/"
echo "  │   └── HotelManagerDashboard.tsx"
echo "  └── components/hotel-management/"
echo "      ├── RoomTypesManagement.tsx"
echo "      ├── EventSpacesManagement.tsx"
echo "      └── BookingsManagement.tsx"
echo ""

# Instruções de integração
echo "🔧 Próximos Passos:"
echo ""
echo "1. Adicionar rotas ao AppRouter.tsx:"
echo "   → Consulte: ROUTING_EXAMPLE.tsx"
echo ""
echo "2. Integrar API com endpoints reais:"
echo "   → Editar useHotels.ts e useEventSpaces.ts"
echo "   → Substituir chamadas de API mockadas por apiService real"
echo ""
echo "3. Adicionar links no navegação principal:"
echo "   → Link para /hotels"
echo "   → Link para /event-spaces"
echo "   → Link para /manager/hotels/:hotelId/dashboard"
echo ""
echo "4. Configurar autenticação de manager:"
echo "   → Verificar se usuário tem acesso ao hotel"
echo "   → Implementar requireHotelOwner middleware"
echo ""
echo "5. Testar localmente:"
echo "   → Verificar se todas as páginas carregam"
echo "   → Testar formulário de busca"
echo "   → Testar dashboard do manager com dados mockados"
echo ""

echo "📚 Documentação:"
echo "  - HOTELS_GUIDE.md          → Guia completo do módulo"
echo "  - ROUTING_EXAMPLE.tsx      → Exemplos de rotas"
echo ""

echo "✅ Setup concluído!"
echo ""
echo "Para começar: npm run dev"
echo ""
